# Logo
logo_image_source: /ashkeys.png
favicon: /ashkeys.png
# Index Page
index_banner_text: AshKeys
index_banner_text_secondary: Confessions and Confusions of Ashok M A. Personal and Professional Blog.
index_font_awesome_icon_css: far fa-star

# Header
menu:
    Home: /
    Portfolio: https://fullstacker.nl
    Sharmi's NFTs: https://ashokma.com/nfts/
    Archives: /archives
    Tags: /tags
    About: /me

# Post
default_post_title: Untitled
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MMM YYYY
archive_font_awesome_icon_css: far fa-folder-open

# About Widget
about_widget_avatar_url: /me/index/avatar.jpeg
about_widget_text: "<b>About Ashok:</b><br/>
Started as <code>Java</code> but mutated myself with some frontend scripting skills and boom Javascript guy
too. Still evolving in the vast <code>NodeJS</code> eco-system.
<ul>
  <li> Backpacker with a bike </li>
  <li> Trying hard to be a violinist </li>
  <li> Reads Medium to know the buzz words and follows developer memes. </li>
</ul>"

# Comments.
comments:
    # Disqus comments
    disqus_shortname:

# Google Analytics Tracking ID
google_analytics: UA-115413748-1

# Social Media Platforms
social_platforms:
    - url: //twitter.com/AshokMA9
      fa_icon: fab fa-twitter
    - url: //www.linkedin.com/in/ashok-m-a-full-stack-dev/
      fa_icon: fab fa-linkedin
    - url: //github.com/Sojiro
      fa_icon: fab fa-github
    - url: //stackoverflow.com/users/1197396/ashok-m-a
      fa_icon: fab fa-stack-overflow

# Footer about
footer_about: "Ashok M A | Powered by <a class='link dim white' href='//hexo.io/'>Hexo</a>"
